---

- name: Pull the configuration file using REST API.
  ansible.builtin.uri:
    method: GET
    url: "{{ fad_base_url + fad_api_endpoint.backup_config }}"
    body_format: "{{ fad_api_uri_params.body_format }}"
    validate_certs: "{{ fad_api_uri_params.validate_certs }}"
    return_content: "{{ fad_api_uri_params.return_content }}"
    status_code: "{{ fad_api_uri_params.status_code }}"
    headers: "{{ fad_api_header }}"
  register: fad_backup_result

- name: Make sure the backup directory exist.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user | default(omit) }}"
    mode: "0644"
  loop:
    - "{{ fad_backup_dir }}"
    - "{{ fad_backup_dir }}/FAD_BACKUP_{{ fad_backup_datestamp }}"
  run_once: true

- name: Write the configuration (in zip binary) into a file.
  ansible.builtin.template:
    src: config_backup.zip.j2
    dest: >
      {{ fad_backup_dir }}/FAD_BACKUP_{{ fad_backup_datestamp }}/{{ fad_backup_datestamp }}_{{ ansible_host }}.zip
    owner: "{{ ansible_user | default(omit) }}"
    mode: "0644"

- name: Zip all the configuration backup files.
  community.general.archive:
    path: "{{ backup_dir }}/FAD_BACKUP_{{ fad_backup_datestamp }}"
    dest: "{{ backup_dir }}/FAD_BACKUP_{{ fad_backup_datestamp }}.zip"
    owner: "{{ ansible_user | default(omit) }}"
    mode: "0644"
  run_once: true
