---
# tasks file for fortiadc-backup

- name: FortiADC Configuration Backup
  ansible.builtin.import_tasks: fad_downloader_config.yaml
  tags: [fad_backup]

- name: Send the the zipped file via SMTP
  community.general.mail:
    host: "{{ fad_backup_mail.smtp_server }}"
    port: "{{ fad_backup_mail.smtp_port }}"
    username: "{{ fad_backup_mail.username | default(omit) }}"
    password: "{{ fad_backup_mail.password | default(omit) }}"
    from: "{{ fad_backup_mail.sender }}"
    to: "{{ fad_backup_mail.recipient }}"
    subject: "{{ fad_backup_mail.subject }}"
    body: "{{ fad_backup_mail.body }}"
    attach: ["{{ fad_backup_dir }}/FAD_BACKUP_{{ fad_backup_datestamp }}.zip"]
  when: fad_backup_send_mail | default('true') | bool  == true
  run_once: true
  tags: [fad_backup]
